from typing import Dict

JOB_DB_APPLICABLE_COLUMNS = {
    "aka_name": [False, False, False, False, True, True, True, False],
    "aka_title": [
        False,
        False,
        False,
        False,
        True,
        True,
        True,
        True,
        True,
        True,
        False,
        False,
    ],
    "cast_info": [False, True, False, True, False, True, True],
    "char_name": [False, False, False, False, True, True, False],
    "comp_cast_type": [False, False],
    "company_name": [False, False, True, False, True, True, False],
    "company_type": [False, False],
    "complete_cast": [False, False, True, True],
    "info_type": [False, False],
    "keyword": [False, False, True],
    "kind_type": [False, False],
    "link_type": [False, False],
    "movie_companies": [False, False, True, True, False],
    "movie_info": [False, False, True, True, False],
    "movie_info_idx": [False, False, True, False, False],
    "movie_keyword": [False, True, True],
    "movie_link": [False, True, True, True],
    "name": [False, False, False, False, True, True, True, True, False],
    "person_info": [False, True, True, False, False],
    "role_type": [False, False],
    "title": [
        False,
        False,
        False,
        True,
        True,
        False,
        True,
        True,
        True,
        True,
        True,
        False,
    ],
}


TPCH_DB_APPLICABLE_COLUMNS = {
    "nation": [False, False, True, False],
    "region": [False, False, False],
    "supplier": [False, False, False, True, False, True, False],
    "customer": [False, False, False, True, False, True, True, False],
    "part": [False, False, True, True, True, True, True, True, False],
    "partsupp": [True, True, True, True, False],
    "orders": [False, True, True, True, True, True, True, True, False],
    "lineitem": [
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        False,
    ],
}

TPCH_TABLE_COLUMN_NAMES = {
    "nation": ["n_nationkey", "n_name", "n_regionkey", "n_comment"],
    "region": ["r_regionkey", "r_name", "r_comment"],
    "supplier": [
        "s_suppkey",
        "s_name",
        "s_address",
        "s_nationkey",
        "s_phone",
        "s_acctbal",
        "s_comment",
    ],
    "customer": [
        "c_custkey",
        "c_name",
        "c_address",
        "c_nationkey",
        "c_phone",
        "c_acctbal",
        "c_mktsegment",
        "c_comment",
    ],
    "part": [
        "p_partkey",
        "p_name",
        "p_mfgr",
        "p_brand",
        "p_type",
        "p_size",
        "p_container",
        "p_retailprice",
        "p_comment",
    ],
    "partsupp": [
        "ps_partkey",
        "ps_suppkey",
        "ps_availqty",
        "ps_supplycost",
        "ps_comment",
    ],
    "orders": [
        "o_orderkey",
        "o_custkey",
        "o_orderstatus",
        "o_totalprice",
        "o_orderdate",
        "o_orderpriority",
        "o_clerk",
        "o_shippriority",
        "o_comment",
    ],
    "lineitem": [
        "l_orderkey",
        "l_partkey",
        "l_suppkey",
        "l_linenumber",
        "l_quantity",
        "l_extendedprice",
        "l_discount",
        "l_tax",
        "l_returnflag",
        "l_linestatus",
        "l_shipdate",
        "l_commitdate",
        "l_receiptdate",
        "l_shipinstruct",
        "l_shipmode",
        "l_comment",
    ],
}

JOB_TABLE_COLUMN_NAMES = {
    "aka_name": [
        "id",
        "person_id",
        "name",
        "imdb_index",
        "name_pcode_cf",
        "name_pcode_nf",
        "surname_pcode",
        "md5sum",
    ],
    "aka_title": [
        "id",
        "movie_id",
        "title",
        "imdb_index",
        "kind_id",
        "production_year",
        "phonetic_code",
        "episode_of_id",
        "season_nr",
        "episode_nr",
        "note",
        "md5sum",
    ],
    "cast_info": [
        "id",
        "person_id",
        "movie_id",
        "person_role_id",
        "note",
        "nr_order",
        "role_id",
    ],
    "char_name": [
        "id",
        "name",
        "imdb_index",
        "imdb_id",
        "name_pcode_nf",
        "surname_pcode",
        "md5sum",
    ],
    "comp_cast_type": ["id", "kind"],
    "company_name": [
        "id",
        "name",
        "country_code",
        "imdb_id",
        "name_pcode_nf",
        "name_pcode_sf",
        "md5sum",
    ],
    "company_type": ["id", "kind"],
    "complete_cast": [
        "id",
        "movie_id",
        "subject_id",
        "status_id",
    ],
    "keyword": [
        "id",
        "keyword",
        "phonetic_code",
    ],
    "kind_type": ["id", "kind"],
    "link_type": ["id", "link"],
    "movie_companies": [
        "id",
        "movie_id",
        "company_id",
        "company_type_id",
        "note",
    ],
    "movie_info": ["id", "movie_id", "info_type_id", "info", "note"],
    "movie_info_idx": ["id", "movie_id", "info_type_id", "info", "note"],
    "movie_keyword": ["id", "movie_id", "keyword_id"],
    "movie_link": ["id", "movie_id", "linked_movie_id", "link_type_id"],
    "name": [
        "id",
        "name",
        "imdb_index",
        "imdb_id",
        "gender",
        "name_pcode_cf",
        "name_pcode_nf",
        "surname_pcode",
        "md5sum",
    ],
    "person_info": ["id", "person_id", "info_type_id", "info", "note"],
    "role_type": ["id", "role"],
    "title": [
        "id",
        "title",
        "imdb_index",
        "kind_id",
        "production_year",
        "imdb_id",
        "phonetic_code",
        "episode_of_id",
        "season_nr",
        "episode_nr",
        "series_years",
        "md5sum",
    ],
}

TPCH_CONFIG = {
    "drift_applicable_columns": TPCH_DB_APPLICABLE_COLUMNS,
    "column_names": TPCH_TABLE_COLUMN_NAMES,
}

JOB_CONFIG = {
    "drift_applicable_columns": JOB_DB_APPLICABLE_COLUMNS,
    "column_names": JOB_TABLE_COLUMN_NAMES,
}

DB_MAP: Dict[str, dict] = {
    "tpch": TPCH_CONFIG,
    "job": JOB_CONFIG,
}
