from typing import Dict


TPCH_DB_APPLICABLE_COLUMNS = {
    "nation": [False, False, True, False],
    "region": [False, False, False],
    "supplier": [False, False, False, True, False, True, False],
    "customer": [False, False, False, True, False, True, True, False],
    "part": [False, False, True, True, True, True, True, True, False],
    "partsupp": [True, True, True, True, False],
    "orders": [False, True, True, True, True, True, True, True, False],
    "lineitem": [
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        False,
    ],
}

TPCH_TABLE_COLUMN_NAMES = {
    "nation": ["n_nationkey", "n_name", "n_regionkey", "n_comment"],
    "region": ["r_regionkey", "r_name", "r_comment"],
    "supplier": [
        "s_suppkey",
        "s_name",
        "s_address",
        "s_nationkey",
        "s_phone",
        "s_acctbal",
        "s_comment",
    ],
    "customer": [
        "c_custkey",
        "c_name",
        "c_address",
        "c_nationkey",
        "c_phone",
        "c_acctbal",
        "c_mktsegment",
        "c_comment",
    ],
    "part": [
        "p_partkey",
        "p_name",
        "p_mfgr",
        "p_brand",
        "p_type",
        "p_size",
        "p_container",
        "p_retailprice",
        "p_comment",
    ],
    "partsupp": [
        "ps_partkey",
        "ps_suppkey",
        "ps_availqty",
        "ps_supplycost",
        "ps_comment",
    ],
    "orders": [
        "o_orderkey",
        "o_custkey",
        "o_orderstatus",
        "o_totalprice",
        "o_orderdate",
        "o_orderpriority",
        "o_clerk",
        "o_shippriority",
        "o_comment",
    ],
    "lineitem": [
        "l_orderkey",
        "l_partkey",
        "l_suppkey",
        "l_linenumber",
        "l_quantity",
        "l_extendedprice",
        "l_discount",
        "l_tax",
        "l_returnflag",
        "l_linestatus",
        "l_shipdate",
        "l_commitdate",
        "l_receiptdate",
        "l_shipinstruct",
        "l_shipmode",
        "l_comment",
    ],
}

TPCH_CONFIG = {
    "drift_applicable_columns": TPCH_DB_APPLICABLE_COLUMNS,
    "column_names": TPCH_TABLE_COLUMN_NAMES,
}

DB_MAP: Dict[str, dict] = {
    "tpch": TPCH_CONFIG,
}