version: '3'

services:
    postgres:
        image: pg_balsa_img
        volumes: 
            - /hdd1/xingnaili/AI4QueryOptimizer/datasets/:/data/datasets
            - ./../../conf/balsa-postgresql.conf:/app/postgresql.conf
            - ./pgdata:/pgdata
        ports:
            - "5432:5432"
        environment:
            - PGDATA=/pgdata
            - POSTGRES_DB=imdbload
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        container_name: pg_balsa
        networks:
            network:
                ipv4_address: 10.6.0.3
        shm_size: 32gb
networks:
    network:
        driver: bridge
        ipam:
            config:
                - subnet: 10.6.0.0/16
