TPCH_DB_APPLICABLE_COLUMNS = {
    "nation": [False, False, True, False],
    "region": [False, False, False],
    "supplier": [False, False, False, True, False, True, False],
    "customer": [False, False, False, True, False, True, True, False],
    "part": [False, False, True, True, True, True, True, True, False],
    "partsupp": [True, True, True, True, False],
    "orders": [False, True, True, True, True, True, True, True, False],
    "lineitem": [
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        False,
    ],
}